steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['image', 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_VERSION_ID}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['image', 'push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_VERSION_ID}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
   - '-c'
   - >
     gcloud deploy releases create release-$BUILD_ID
     --delivery-pipeline=flask-app
     --region=us-central1
     --source=./
     --images=flask=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${_VERSION_ID}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO_NAME: my-docker-repo
  _IMAGE_NAME: flaskapp
  _VERSION_ID: $SHORT_SHA
